import { Archetype, Gender, Skill } from './types';

// --- Archetypes (10M, 10F, 6O) ---

export const ARCHETYPES: Record<Gender, Archetype[]> = {
  [Gender.MALE]: [
    {
      id: 'm_alpha',
      name: '冷酷学霸',
      description: '眼神锐利，智商超群，对恋爱毫无兴趣的禁欲系。',
      icon: 'Glasses',
      baseBonus: { $潜力: 1.0, $基础忍耐力: 5 },
      passiveSkill: {
        id: 'p_analysis',
        name: '真理之眼',
        description: '看穿对方敏感点',
        type: 'constitution',
        icon: 'Eye',
      },
    },
    {
      id: 'm_wild',
      name: '狂野校霸',
      description: '充满野性与侵略性，无论在哪里都是绝对的支配者。',
      icon: 'Sword',
      baseBonus: { _最大耐力: 20, $基础性斗力: 5, _声望: -50 },
      passiveSkill: {
        id: 'p_domination',
        name: '绝对支配',
        description: '高潮边缘指令成功率提升',
        type: 'constitution',
        icon: 'Crown',
      },
    },
    {
      id: 'm_schemer',
      name: '腹黑军师',
      description: '表面温文尔雅，实则城府极深，控制欲极强。',
      icon: 'Brain',
      baseBonus: { $潜力: 0.5, _幸运: 15, $暴击率: 5 },
      passiveSkill: {
        id: 'p_pokerface',
        name: '笑面虎',
        description: '难以被心理攻势影响',
        type: 'constitution',
        icon: 'Ghost',
      },
    },
    {
      id: 'm_prince',
      name: '温柔王子',
      description: '如同童话中走出一般，对所有人都温柔体贴的现充。',
      icon: 'Crown',
      baseBonus: { _魅力: 20, _声望: 100 },
      passiveSkill: {
        id: 'p_gentle',
        name: '暖男光环',
        description: '初始好感度提升',
        type: 'constitution',
        icon: 'Sparkles',
      },
    },
    {
      id: 'm_femboy',
      name: '娇俏伪娘',
      description: '比女生更可爱的小男娘，容易激起保护欲。',
      icon: 'Cat',
      baseBonus: { _魅力: 15, _最大快感: 20, $闪避率: 5 },
      passiveSkill: {
        id: 'p_confusion',
        name: '性别模糊',
        description: '让直男陷入混乱',
        type: 'constitution',
        icon: 'RefreshCcw',
      },
    },
    {
      id: 'm_shota',
      name: '可爱正太',
      description: '外表人畜无害，实际上可能切开是黑的年下系。',
      icon: 'Smile',
      baseBonus: { _幸运: 20, _最大快感: 10 },
      passiveSkill: {
        id: 'p_innocent',
        name: '无辜防御',
        description: '概率使对方中止攻击',
        type: 'constitution',
        icon: 'Shield',
      },
    },
    {
      id: 'm_jock',
      name: '体育特长生',
      description: '阳光开朗大男孩，体力无限，但心思比较单纯。',
      icon: 'Dumbbell',
      baseBonus: { _最大耐力: 40, $基础性斗力: 3 },
      passiveSkill: {
        id: 'p_stamina',
        name: '无限体能',
        description: '耐力恢复速度翻倍',
        type: 'constitution',
        icon: 'Zap',
      },
    },
    {
      id: 'm_otaku',
      name: '技术宅',
      description: '虽不善言辞，但在某些奇怪的领域拥有惊人的知识储备。',
      icon: 'Wifi',
      baseBonus: { $潜力: 2.0, $暴击率: 10, _魅力: -10 },
      passiveSkill: {
        id: 'p_tech',
        name: '道具改装',
        description: '道具效果大幅提升',
        type: 'constitution',
        icon: 'Settings',
      },
    },
    {
      id: 'm_narcissist',
      name: '自恋狂',
      description: '沉醉于自己的美貌，随身携带镜子，认为全世界都爱自己。',
      icon: 'Mirror',
      baseBonus: { _魅力: 25, _声望: -10 },
      passiveSkill: {
        id: 'p_mirror',
        name: '自我陶醉',
        description: '免疫降低魅力的效果',
        type: 'constitution',
        icon: 'Sparkles',
      },
    },
    {
      id: 'm_delinquent',
      name: '不良少年',
      description: '并不坏，只是不想被束缚，喜欢在危险边缘试探。',
      icon: 'Skull',
      baseBonus: { $基础性斗力: 8, _堕落度: 10, _幸运: -5 },
      passiveSkill: {
        id: 'p_risk',
        name: '背水一战',
        description: '耐力越低性斗力越高',
        type: 'constitution',
        icon: 'Flame',
      },
    },
  ],
  [Gender.FEMALE]: [
    {
      id: 'f_onee',
      name: '成熟御姐',
      description: '气场强大，身材惹火，举手投足间散发着致命魅力。',
      icon: 'Crown',
      baseBonus: { _魅力: 15, $基础性斗力: 5, _最大快感: 20 },
      passiveSkill: {
        id: 'p_araara',
        name: '大姐姐领域',
        description: '对年下角色压迫力翻倍',
        type: 'constitution',
        icon: 'Target',
      },
    },
    {
      id: 'f_sweet',
      name: '甜美软妹',
      description: '治愈系的笑容，温柔体贴，像是棉花糖一样柔软。',
      icon: 'Heart',
      baseBonus: { _幸运: 15, _魅力: 10, $基础忍耐力: 5 },
      passiveSkill: {
        id: 'p_healing',
        name: '治愈体质',
        description: '回合结束恢复体力',
        type: 'constitution',
        icon: 'Heart',
      },
    },
    {
      id: 'f_loli',
      name: '娇小萝莉',
      description: '体型娇小可爱，拥有令人怜惜的外表和惊人的潜力。',
      icon: 'Sparkles',
      baseBonus: { $潜力: 2.0, $闪避率: 10 },
      passiveSkill: {
        id: 'p_smallbody',
        name: '紧致构造',
        description: '双方快感积累速度提升',
        type: 'constitution',
        icon: 'Zap',
      },
    },
    {
      id: 'f_mesugaki',
      name: '雌小鬼',
      description: '性格恶劣，喜欢嘲讽，但在吃瘪时会露出绝妙表情。',
      icon: 'Ghost',
      baseBonus: { $基础性斗力: 10, _最大耐力: -20, _最大快感: 30 },
      passiveSkill: {
        id: 'p_glass_cannon',
        name: '杂鱼判定',
        description: '嘲讽造成暴击，但自身极易高潮',
        type: 'constitution',
        icon: 'Flame',
      },
    },
    {
      id: 'f_cool',
      name: '冰山美人',
      description: '拒人于千里之外的冷漠，只为特定的人融化。',
      icon: 'Glasses',
      baseBonus: { $基础忍耐力: 10, _魅力: 5 },
      passiveSkill: {
        id: 'p_cold',
        name: '绝对零度',
        description: '极难进入兴奋状态',
        type: 'constitution',
        icon: 'Shield',
      },
    },
    {
      id: 'f_gyaru',
      name: '黑皮辣妹',
      description: '健康的小麦色皮肤，性格豪爽，玩得很花。',
      icon: 'Zap',
      baseBonus: { _最大耐力: 30, _堕落度: 20 },
      passiveSkill: {
        id: 'p_endurance',
        name: '无限精力',
        description: '多人场景全属性提升',
        type: 'constitution',
        icon: 'Zap',
      },
    },
    {
      id: 'f_traditional',
      name: '大和抚子',
      description: '传统的大家闺秀，温婉贤淑，拥有极强的忍耐力。',
      icon: 'Flower',
      baseBonus: { _声望: 50, _最大快感: -10 },
      passiveSkill: {
        id: 'p_patience',
        name: '隐忍不发',
        description: '受到攻击时忍耐力消耗减半',
        type: 'constitution',
        icon: 'Feather',
      },
    },
    {
      id: 'f_yandere',
      name: '病娇',
      description: '爱意沉重到令人窒息，为了爱可以摧毁一切。',
      icon: 'Scissors',
      baseBonus: { $基础性斗力: 15, $暴击率: 20 },
      passiveSkill: {
        id: 'p_obsession',
        name: '爱之深',
        description: '对手快感越高，自身攻击越高',
        type: 'constitution',
        icon: 'Skull',
      },
    },
    {
      id: 'f_chuuni',
      name: '中二病',
      description: '坚信自己拥有特殊力量的电波系少女。',
      icon: 'Eye',
      baseBonus: { $潜力: 1.5, _幸运: 20, _魅力: -5 },
      passiveSkill: {
        id: 'p_delusion',
        name: '妄想结界',
        description: '随机免疫异常状态',
        type: 'constitution',
        icon: 'Sparkles',
      },
    },
    {
      id: 'f_bimbo',
      name: '笨蛋美人',
      description: '拥有顶级的身材与美貌，但脑袋空空，极易被诱骗。',
      icon: 'Gem',
      baseBonus: { _魅力: 30, _最大快感: 30 },
      passiveSkill: {
        id: 'p_airhead',
        name: '无防备',
        description: '所有控制类技能必定命中',
        type: 'constitution',
        icon: 'HelpCircle',
      },
    },
  ],
  [Gender.OTHER]: [
    {
      id: 'o_succubus',
      name: '魅魔体质',
      description: '以精气为食，生来就是为了掠夺快感的特殊存在。',
      icon: 'Heart',
      baseBonus: { _最大快感: 50, _魅力: 20, $基础性斗力: 5 },
      passiveSkill: {
        id: 'p_drain',
        name: '精气汲取',
        description: '高潮时吸取对方体力',
        type: 'constitution',
        icon: 'Heart',
      },
    },
    {
      id: 'o_mystery',
      name: '克苏鲁',
      description: '无法被定义的某种存在，充满未知的诱惑与恐惧。',
      icon: 'Ghost',
      baseBonus: { $潜力: 3.0 },
      passiveSkill: {
        id: 'p_chaos',
        name: '不可名状',
        description: '身体构造可随心改变',
        type: 'constitution',
        icon: 'Ghost',
      },
    },
    {
      id: 'o_futa',
      name: '扶她',
      description: '兼具两性特征，拥有超越常人的精力与征服欲。',
      icon: 'Sword',
      baseBonus: { _最大耐力: 30, $基础性斗力: 10, _最大快感: 20 },
      passiveSkill: {
        id: 'p_dual',
        name: '双重快感',
        description: '虽然有两倍敏感点，但也有两倍爆发力',
        type: 'constitution',
        icon: 'Zap',
      },
    },
    {
      id: 'o_doll',
      name: '活体人偶',
      description: '精致如人偶般的存在，痛觉迟钝，唯命是从。',
      icon: 'User',
      baseBonus: { $基础忍耐力: 20, _魅力: 25 },
      passiveSkill: {
        id: 'p_doll',
        name: '无心之躯',
        description: '大幅降低受到的精神伤害',
        type: 'constitution',
        icon: 'Shield',
      },
    },
    {
      id: 'o_beast',
      name: '兽化人',
      description: '保留了野兽本能的亚人，感官敏锐，行动迅捷。',
      icon: 'Cat',
      baseBonus: { $闪避率: 20, _最大耐力: 15 },
      passiveSkill: {
        id: 'p_instinct',
        name: '野性直觉',
        description: '必定闪避致命的一击',
        type: 'constitution',
        icon: 'Wind',
      },
    },
    {
      id: 'o_cyborg',
      name: '机娘',
      description: '全身义体化的改造人，拥有精密的计算能力与震动功能。',
      icon: 'Cpu',
      baseBonus: { _最大耐力: 50, _最大快感: -20, $基础性斗力: 5 },
      passiveSkill: {
        id: 'p_vibrate',
        name: '高频震动',
        description: '接触即造成持续快感伤害',
        type: 'constitution',
        icon: 'Zap',
      },
    },
  ],
};

// --- Active Skills (20+) ---

export const ACTIVE_SKILLS: Skill[] = [
  {
    id: 's_strip',
    name: '衣物破坏',
    description: '【攻击】强行撕裂对方衣物',
    effectDescription: '减少对方防御',
    type: 'active',
    icon: 'Scissors',
  },
  {
    id: 's_tease',
    name: '指尖挑逗',
    description: '【攻击】精细的爱抚敏感点',
    effectDescription: '造成少量快感',
    type: 'active',
    icon: 'Hand',
  },
  {
    id: 's_observe',
    name: '弱点洞察',
    description: '【辅助】观察对方身体',
    effectDescription: '下回合暴击率提升',
    type: 'active',
    icon: 'Eye',
  },
  {
    id: 's_kiss',
    name: '深吻',
    description: '【攻击】交换唾液的深吻',
    effectDescription: '造成快感并封锁语言',
    type: 'active',
    icon: 'Heart',
  },
  {
    id: 's_spank',
    name: '羞耻拍打',
    description: '【攻击】拍打臀部',
    effectDescription: '增加对方羞耻与快感',
    type: 'active',
    icon: 'Hand',
  },
  {
    id: 's_dirtytalk',
    name: '污言秽语',
    description: '【精神】用言语侮辱对方',
    effectDescription: '降低对方忍耐力',
    type: 'active',
    icon: 'Music',
  },
  {
    id: 's_pheromone',
    name: '费洛蒙',
    description: '【领域】散发催情气味',
    effectDescription: '每回合持续增加快感',
    type: 'active',
    icon: 'Wind',
  },
  {
    id: 's_camera',
    name: '偷拍视角',
    description: '【精神】记录羞耻画面',
    effectDescription: '大幅降低对方忍耐力',
    type: 'active',
    icon: 'Camera',
  },
  {
    id: 's_toy',
    name: '道具使用',
    description: '【特殊】使用随身玩具',
    effectDescription: '效果取决于道具',
    type: 'active',
    icon: 'Zap',
  },
  {
    id: 's_foot',
    name: '足技',
    description: '【攻击】用脚挑逗',
    effectDescription: '带有羞辱性质的快感',
    type: 'active',
    icon: 'Footprints',
  },
  {
    id: 's_bind',
    name: '束缚',
    description: '【控制】限制对方行动',
    effectDescription: '降低对方闪避率',
    type: 'active',
    icon: 'Anchor',
  },
  {
    id: 's_massage',
    name: '精油按摩',
    description: '【特殊】推油按摩',
    effectDescription: '降低防御，增加敏感度',
    type: 'active',
    icon: 'Droplets',
  },
  {
    id: 's_flash',
    name: '露出',
    description: '【精神】展示私密部位',
    effectDescription: '对纯情角色造成暴击',
    type: 'active',
    icon: 'Eye',
  },
  {
    id: 's_beg',
    name: '求饶',
    description: '【防御】楚楚可怜地求饶',
    effectDescription: '降低对方性斗力',
    type: 'active',
    icon: 'Smile',
  },
  {
    id: 's_taunt',
    name: '挑衅',
    description: '【精神】嘲讽对方的技术',
    effectDescription: '增加对方怒气但降低防御',
    type: 'active',
    icon: 'Ghost',
  },
  {
    id: 's_force',
    name: '强行压制',
    description: '【控制】利用体格压制',
    effectDescription: '封锁对方物理行动',
    type: 'active',
    icon: 'Dumbbell',
  },
  {
    id: 's_deny',
    name: '寸止',
    description: '【特殊】在关键时刻停手',
    effectDescription: '积累大量压力值',
    type: 'active',
    icon: 'Hand',
  },
  {
    id: 's_worship',
    name: '崇拜',
    description: '【精神】奉对方为主人',
    effectDescription: '回复对方耐力，降低自身耐力',
    type: 'active',
    icon: 'Crown',
  },
  {
    id: 's_aphrodisiac',
    name: '媚药投毒',
    description: '【道具】悄悄下药',
    effectDescription: '赋予持续发情状态',
    type: 'active',
    icon: 'FlaskConical',
  },
  {
    id: 's_charm_kiss',
    name: '魅惑之吻',
    description: '【攻击】用魅惑的吻技攻击',
    effectDescription: '造成50%魅力伤害，降低目标忍耐力',
    type: 'active',
    icon: 'Heart',
  },
  {
    id: 's_counter',
    name: '快速反击',
    description: '【攻击】在闪避后立即反击',
    effectDescription: '造成80%性斗力伤害，无视防御',
    type: 'active',
    icon: 'Shield',
  },
  {
    id: 's_lucky_strike',
    name: '幸运一击',
    description: '【攻击】依靠运气发动的强力攻击',
    effectDescription: '造成60%性斗力+40%幸运伤害',
    type: 'active',
    icon: 'Clover',
  },
];

// --- Constitution/Passive Skills (Gender Specific) ---

const COMMON_PASSIVES: Skill[] = [
  {
    id: 'c_thick_skin',
    name: '钝感',
    description: '感官比较迟钝',
    effectDescription: '受到的快感伤害-30%',
    type: 'constitution',
    icon: 'Shield',
  },
  {
    id: 'c_quick_recovery',
    name: '回复体质',
    description: '体力恢复很快',
    effectDescription: '每回合回复5%耐力',
    type: 'constitution',
    icon: 'Zap',
  },
  {
    id: 'c_flexible',
    name: '身体柔软',
    description: '可以做出高难度动作',
    effectDescription: '闪避率+10%，解锁特殊体位',
    type: 'constitution',
    icon: 'Wind',
  },
  {
    id: 'c_exhibitionist',
    name: '暴露狂',
    description: '被人注视会兴奋',
    effectDescription: '围观人数越多全属性越高',
    type: 'constitution',
    icon: 'Eye',
  },
  {
    id: 'c_m_physique',
    name: 'M属性',
    description: '享受痛苦与羞辱',
    effectDescription: '受到的精神伤害转化为快感',
    type: 'constitution',
    icon: 'Heart',
  },
  {
    id: 'c_s_physique',
    name: 'S属性',
    description: '以施虐为乐',
    effectDescription: '攻击造成额外精神伤害',
    type: 'constitution',
    icon: 'Sword',
  },
];

export const PASSIVE_SKILLS: Record<Gender, Skill[]> = {
  [Gender.MALE]: [
    ...COMMON_PASSIVES,
    {
      id: 'c_iron_cock',
      name: '钢铁巨根',
      description: '坚硬如铁',
      effectDescription: '攻击力+20%',
      type: 'constitution',
      icon: 'Dumbbell',
    },
    {
      id: 'c_stamina_monster',
      name: '耐力怪物',
      description: '不知疲倦',
      effectDescription: '最大耐力+100',
      type: 'constitution',
      icon: 'Zap',
    },
    {
      id: 'c_prostate_master',
      name: '前列腺开发',
      description: '弱点开发',
      effectDescription: '后庭敏感度x3',
      type: 'constitution',
      icon: 'Target',
    },
  ],
  [Gender.FEMALE]: [
    ...COMMON_PASSIVES,
    {
      id: 'c_sensitive_nips',
      name: '乳首开发',
      description: '胸部极为敏感',
      effectDescription: '胸部受到攻击快感x2',
      type: 'constitution',
      icon: 'Target',
    },
    {
      id: 'c_wet',
      name: '淫乱体质',
      description: '极易动情',
      effectDescription: '初始快感+20，爱液分泌增加',
      type: 'constitution',
      icon: 'Droplets',
    },
    {
      id: 'c_dry',
      name: '石女/白虎',
      description: '难以动情',
      effectDescription: '快感积累速度-20%',
      type: 'constitution',
      icon: 'Mountain',
    },
    {
      id: 'c_tongue',
      name: '名器之舌',
      description: '舌头灵活',
      effectDescription: '口技效果+50%',
      type: 'constitution',
      icon: 'Flame',
    },
    {
      id: 'c_voice',
      name: '娇喘',
      description: '声音好听',
      effectDescription: '受击时的叫声会对周围造成精神伤害',
      type: 'constitution',
      icon: 'Music',
    },
    {
      id: 'c_scent',
      name: '体香',
      description: '天生自带香气',
      effectDescription: '对手每回合忍耐力-2',
      type: 'constitution',
      icon: 'Flower',
    },
  ],
  [Gender.OTHER]: [
    ...COMMON_PASSIVES,
    {
      id: 'c_sensitive_nips',
      name: '乳首开发',
      description: '胸部极为敏感',
      effectDescription: '胸部受到攻击快感x2',
      type: 'constitution',
      icon: 'Target',
    },
    {
      id: 'c_wet',
      name: '淫乱体质',
      description: '极易动情',
      effectDescription: '初始快感+20，爱液分泌增加',
      type: 'constitution',
      icon: 'Droplets',
    },
    {
      id: 'c_voice',
      name: '娇喘',
      description: '声音好听',
      effectDescription: '受击时的叫声会对周围造成精神伤害',
      type: 'constitution',
      icon: 'Music',
    },
    {
      id: 'c_scent',
      name: '体香',
      description: '天生自带香气',
      effectDescription: '对手每回合忍耐力-2',
      type: 'constitution',
      icon: 'Flower',
    },
    {
      id: 'c_mutable',
      name: '不定形',
      description: '身体结构不稳定',
      effectDescription: '免疫暴击',
      type: 'constitution',
      icon: 'Ghost',
    },
  ],
};

export const MAX_STATS = {
  _等级: 100,
  $潜力: 10.0,
  _魅力: 100,
  _幸运: 100,
  _最大耐力: 500,
  _最大快感: 500,
  // Others are derived or fixed cap
};

export const DIFFICULTY_POINTS = {
  '剧情模式 (简单)': 100,
  '学园生活 (普通)': 60,
  '地狱开局 (困难)': 30,
  作弊者: 999,
};

export const CUP_SIZES = ['AA', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I+', 'Z'];

export const GENITAL_TYPES = {
  [Gender.MALE]: ['标准', '巨根', '短小', '包茎', '形状优美', '青筋暴露', '珍珠疹', '极粗', '倒钩', '发光'],
  [Gender.FEMALE]: ['标准', '白虎', '馒头穴', '一线天', '蝴蝶穴', '粉嫩', '色素沉淀', '多水', '紧致', '名器'],
  [Gender.OTHER]: ['扶她', '无性', '触手', '双性', '异形', '机械接口', '虚空', '植物', '灵体'],
};
