import { Archetype, Gender, Skill } from './types';

// --- Archetypes (10M, 10F, 6O) ---
// 每个角色只有不同的 passiveSkill 和 permanentState，没有 baseBonus

export const ARCHETYPES: Record<Gender, Archetype[]> = {
  [Gender.MALE]: [
    {
      id: 'm_alpha',
      name: '冷酷学霸',
      description: '眼神锐利，智商超群，对恋爱毫无兴趣的禁欲系。',
      icon: 'Glasses',
      passiveSkill: {
        id: 'p_analysis',
        name: '真理之眼',
        description: '看穿对方敏感点',
        type: 'constitution',
        icon: 'Eye',
      },
      permanentState: {
        name: '禁欲学者',
        bonus: {
          魅力加成: -5,
          幸运加成: 0,
          基础性斗力加成: 0,
          基础性斗力成算: 0,
          基础忍耐力加成: 0,
          基础忍耐力成算: 20,
          闪避率加成: 0,
          暴击率加成: 15,
        },
      },
    },
    {
      id: 'm_wild',
      name: '狂野校霸',
      description: '充满野性与侵略性，无论在哪里都是绝对的支配者。',
      icon: 'Sword',
      passiveSkill: {
        id: 'p_domination',
        name: '绝对支配',
        description: '高潮边缘指令成功率提升',
        type: 'constitution',
        icon: 'Crown',
      },
      permanentState: {
        name: '野性支配',
        bonus: {
          魅力加成: -10,
          幸运加成: -5,
          基础性斗力加成: 0,
          基础性斗力成算: 25,
          基础忍耐力加成: 0,
          基础忍耐力成算: 0,
          闪避率加成: 0,
          暴击率加成: 20,
        },
      },
    },
    {
      id: 'm_schemer',
      name: '腹黑军师',
      description: '表面温文尔雅，实则城府极深，控制欲极强。',
      icon: 'Brain',
      passiveSkill: {
        id: 'p_pokerface',
        name: '笑面虎',
        description: '难以被心理攻势影响',
        type: 'constitution',
        icon: 'Ghost',
      },
      permanentState: {
        name: '深谋远虑',
        bonus: {
          魅力加成: 8,
          幸运加成: 15,
          基础性斗力加成: 0,
          基础性斗力成算: 0,
          基础忍耐力加成: 0,
          基础忍耐力成算: 0,
          闪避率加成: 10,
          暴击率加成: 12,
        },
      },
    },
    {
      id: 'm_prince',
      name: '温柔王子',
      description: '如同童话中走出一般，对所有人都温柔体贴的现充。',
      icon: 'Crown',
      passiveSkill: {
        id: 'p_gentle',
        name: '暖男光环',
        description: '初始好感度提升',
        type: 'constitution',
        icon: 'Sparkles',
      },
      permanentState: {
        name: '温柔光环',
        bonus: {
          魅力加成: 20,
          幸运加成: 10,
          基础性斗力加成: 0,
          基础性斗力成算: -30,
          基础忍耐力加成: 0,
          基础忍耐力成算: 15,
          闪避率加成: 0,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'm_femboy',
      name: '娇俏伪娘',
      description: '比女生更可爱的小男娘，容易激起保护欲。',
      icon: 'Cat',
      passiveSkill: {
        id: 'p_confusion',
        name: '性别模糊',
        description: '让直男陷入混乱',
        type: 'constitution',
        icon: 'RefreshCcw',
      },
      permanentState: {
        name: '娇柔体质',
        bonus: {
          魅力加成: 40,
          幸运加成: 15,
          基础性斗力加成: 0,
          基础性斗力成算: -40,
          基础忍耐力加成: 0,
          基础忍耐力成算: -40,
          闪避率加成: 20,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'm_shota',
      name: '可爱正太',
      description: '外表人畜无害，实际上可能切开是黑的年下系。',
      icon: 'Smile',
      passiveSkill: {
        id: 'p_innocent',
        name: '无辜防御',
        description: '概率使对方中止攻击',
        type: 'constitution',
        icon: 'Shield',
      },
      permanentState: {
        name: '纯真外表',
        bonus: {
          魅力加成: 10,
          幸运加成: 20,
          基础性斗力加成: 0,
          基础性斗力成算: -50,
          基础忍耐力加成: 0,
          基础忍耐力成算: 0,
          闪避率加成: 18,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'm_jock',
      name: '体育特长生',
      description: '阳光开朗大男孩，体力无限，但心思比较单纯。',
      icon: 'Dumbbell',
      passiveSkill: {
        id: 'p_stamina',
        name: '无限体能',
        description: '耐力恢复速度翻倍',
        type: 'constitution',
        icon: 'Zap',
      },
      permanentState: {
        name: '运动健将',
        bonus: {
          魅力加成: -5,
          幸运加成: 0,
          基础性斗力加成: 0,
          基础性斗力成算: 15,
          基础忍耐力加成: 0,
          基础忍耐力成算: 30,
          闪避率加成: 0,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'm_otaku',
      name: '技术宅',
      description: '虽不善言辞，但在某些奇怪的领域拥有惊人的知识储备。',
      icon: 'Wifi',
      passiveSkill: {
        id: 'p_tech',
        name: '道具改装',
        description: '道具效果大幅提升',
        type: 'constitution',
        icon: 'Settings',
      },
      permanentState: {
        name: '技术专精',
        bonus: {
          魅力加成: -15,
          幸运加成: 0,
          基础性斗力加成: 0,
          基础性斗力成算: 0,
          基础忍耐力加成: 0,
          基础忍耐力成算: -25,
          闪避率加成: 0,
          暴击率加成: 25,
        },
      },
    },
    {
      id: 'm_narcissist',
      name: '自恋狂',
      description: '沉醉于自己的美貌，随身携带镜子，认为全世界都爱自己。',
      icon: 'Mirror',
      passiveSkill: {
        id: 'p_mirror',
        name: '自我陶醉',
        description: '免疫降低魅力的效果',
        type: 'constitution',
        icon: 'Sparkles',
      },
      permanentState: {
        name: '自我中心',
        bonus: {
          魅力加成: 30,
          幸运加成: -10,
          基础性斗力加成: 0,
          基础性斗力成算: 0,
          基础忍耐力加成: 0,
          基础忍耐力成算: 0,
          闪避率加成: 0,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'm_delinquent',
      name: '不良少年',
      description: '并不坏，只是不想被束缚，喜欢在危险边缘试探。',
      icon: 'Skull',
      passiveSkill: {
        id: 'p_risk',
        name: '背水一战',
        description: '耐力越低性斗力越高',
        type: 'constitution',
        icon: 'Flame',
      },
      permanentState: {
        name: '危险边缘',
        bonus: {
          魅力加成: -5,
          幸运加成: -10,
          基础性斗力加成: 0,
          基础性斗力成算: 35,
          基础忍耐力加成: 0,
          基础忍耐力成算: -30,
          闪避率加成: 0,
          暴击率加成: 18,
        },
      },
    },
    {
      id: 'm_gloomy',
      name: '好色少年',
      description: '单纯好色，所以很多事情都是因为好色导致的。',
      icon: 'Heart',
      passiveSkill: {
        id: 'p_invisibility',
        name: '背水一战',
        description: '降低被针对的概率',
        type: 'constitution',
        icon: 'Flame',
      },
      permanentState: {
        name: '背水一战',
        bonus: {
          魅力加成: -20,
          幸运加成: 15,
          基础性斗力加成: 30,
          基础性斗力成算: 0,
          基础忍耐力加成: 0,
          基础忍耐力成算: 0,
          闪避率加成: 0,
          暴击率加成: 0,
        },
      },
    },
  ],
  [Gender.FEMALE]: [
    {
      id: 'f_onee',
      name: '成熟御姐',
      description: '气场强大，身材惹火，举手投足间散发着致命魅力。',
      icon: 'Crown',
      passiveSkill: {
        id: 'p_araara',
        name: '大姐姐领域',
        description: '对年下角色压迫力翻倍',
        type: 'constitution',
        icon: 'Target',
      },
      permanentState: {
        name: '成熟魅力',
        bonus: {
          魅力加成: 18,
          幸运加成: 0,
          基础性斗力加成: 0,
          基础性斗力成算: 20,
          基础忍耐力加成: 0,
          基础忍耐力成算: -15,
          闪避率加成: 0,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'f_sweet',
      name: '甜美软妹',
      description: '治愈系的笑容，温柔体贴，像是棉花糖一样柔软。',
      icon: 'Heart',
      passiveSkill: {
        id: 'p_healing',
        name: '治愈体质',
        description: '回合结束恢复体力',
        type: 'constitution',
        icon: 'Heart',
      },
      permanentState: {
        name: '治愈之光',
        bonus: {
          魅力加成: 15,
          幸运加成: 15,
          基础性斗力加成: 0,
          基础性斗力成算: -25,
          基础忍耐力加成: 0,
          基础忍耐力成算: 25,
          闪避率加成: 0,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'f_loli',
      name: '娇小萝莉',
      description: '体型娇小可爱，拥有令人怜惜的外表和惊人的潜力。',
      icon: 'Sparkles',
      passiveSkill: {
        id: 'p_smallbody',
        name: '紧致构造',
        description: '双方快感积累速度提升',
        type: 'constitution',
        icon: 'Zap',
      },
      permanentState: {
        name: '娇小潜力',
        bonus: {
          魅力加成: 20,
          幸运加成: 20,
          基础性斗力加成: 0,
          基础性斗力成算: -40,
          基础忍耐力加成: 0,
          基础忍耐力成算: -40,
          闪避率加成: 20,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'f_mesugaki',
      name: '雌小鬼',
      description: '性格恶劣，喜欢嘲讽，但在吃瘪时会露出绝妙表情。',
      icon: 'Ghost',
      passiveSkill: {
        id: 'p_glass_cannon',
        name: '杂鱼判定',
        description: '嘲讽造成暴击，但自身极易高潮',
        type: 'constitution',
        icon: 'Flame',
      },
      permanentState: {
        name: '玻璃大炮',
        bonus: {
          魅力加成: -8,
          幸运加成: 20,
          基础性斗力加成: 0,
          基础性斗力成算: 70,
          基础忍耐力加成: 0,
          基础忍耐力成算: -70,
          闪避率加成: 0,
          暴击率加成: 20,
        },
      },
    },
    {
      id: 'f_cool',
      name: '冰山美人',
      description: '拒人于千里之外的冷漠，只为特定的人融化。',
      icon: 'Glasses',
      passiveSkill: {
        id: 'p_cold',
        name: '绝对零度',
        description: '极难进入兴奋状态',
        type: 'constitution',
        icon: 'Shield',
      },
      permanentState: {
        name: '冰霜之心',
        bonus: {
          魅力加成: 8,
          幸运加成: -10,
          基础性斗力加成: 0,
          基础性斗力成算: -20,
          基础忍耐力加成: 0,
          基础忍耐力成算: 40,
          闪避率加成: 10,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'f_gyaru',
      name: '黑皮辣妹',
      description: '健康的小麦色皮肤，性格豪爽，玩得很花。',
      icon: 'Zap',
      passiveSkill: {
        id: 'p_endurance',
        name: '无限精力',
        description: '多人场景全属性提升',
        type: 'constitution',
        icon: 'Zap',
      },
      permanentState: {
        name: '活力四射',
        bonus: {
          魅力加成: -5,
          幸运加成: 10,
          基础性斗力加成: 0,
          基础性斗力成算: 18,
          基础忍耐力加成: 0,
          基础忍耐力成算: 25,
          闪避率加成: 0,
          暴击率加成: 8,
        },
      },
    },
    {
      id: 'f_traditional',
      name: '大和抚子',
      description: '传统的大家闺秀，温婉贤淑，拥有极强的忍耐力。',
      icon: 'Flower',
      passiveSkill: {
        id: 'p_patience',
        name: '隐忍不发',
        description: '受到攻击时忍耐力消耗减半',
        type: 'constitution',
        icon: 'Feather',
      },
      permanentState: {
        name: '传统美德',
        bonus: {
          魅力加成: 12,
          幸运加成: 8,
          基础性斗力加成: 0,
          基础性斗力成算: -35,
          基础忍耐力加成: 0,
          基础忍耐力成算: 45,
          闪避率加成: 0,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'f_yandere',
      name: '病娇',
      description: '爱意沉重到令人窒息，为了爱可以摧毁一切。',
      icon: 'Scissors',
      passiveSkill: {
        id: 'p_obsession',
        name: '爱之深',
        description: '对手快感越高，自身攻击越高',
        type: 'constitution',
        icon: 'Skull',
      },
      permanentState: {
        name: '病态执着',
        bonus: {
          魅力加成: 8,
          幸运加成: -10,
          基础性斗力加成: 0,
          基础性斗力成算: 40,
          基础忍耐力加成: 0,
          基础忍耐力成算: -30,
          闪避率加成: 0,
          暴击率加成: 25,
        },
      },
    },
    {
      id: 'f_chuuni',
      name: '中二病',
      description: '坚信自己拥有特殊力量的电波系少女。',
      icon: 'Eye',
      passiveSkill: {
        id: 'p_delusion',
        name: '妄想结界',
        description: '随机免疫异常状态',
        type: 'constitution',
        icon: 'Sparkles',
      },
      permanentState: {
        name: '中二之力',
        bonus: {
          魅力加成: -10,
          幸运加成: 25,
          基础性斗力加成: 0,
          基础性斗力成算: 0,
          基础忍耐力加成: 0,
          基础忍耐力成算: -20,
          闪避率加成: 0,
          暴击率加成: 15,
        },
      },
    },
    {
      id: 'f_bimbo',
      name: '笨蛋美人',
      description: '拥有顶级的身材与美貌，但脑袋空空，极易被诱骗。',
      icon: 'Gem',
      passiveSkill: {
        id: 'p_airhead',
        name: '无防备',
        description: '所有控制类技能必定命中',
        type: 'constitution',
        icon: 'HelpCircle',
      },
      permanentState: {
        name: '无脑美人',
        bonus: {
          魅力加成: 40,
          幸运加成: 10,
          基础性斗力加成: 0,
          基础性斗力成算: -50,
          基础忍耐力加成: 0,
          基础忍耐力成算: -40,
          闪避率加成: 0,
          暴击率加成: 0,
        },
      },
    },
  ],
  [Gender.OTHER]: [
    {
      id: 'o_succubus',
      name: '魅魔体质',
      description: '以精气为食，生来就是为了掠夺快感的特殊存在。',
      icon: 'Heart',
      passiveSkill: {
        id: 'p_drain',
        name: '精气汲取',
        description: '高潮时吸取对方体力',
        type: 'constitution',
        icon: 'Heart',
      },
      permanentState: {
        name: '魅魔之体',
        bonus: {
          魅力加成: 25,
          幸运加成: 12,
          基础性斗力加成: 0,
          基础性斗力成算: 22,
          基础忍耐力加成: 0,
          基础忍耐力成算: -35,
          闪避率加成: 0,
          暴击率加成: 15,
        },
      },
    },
    {
      id: 'o_mystery',
      name: '克苏鲁',
      description: '无法被定义的某种存在，充满未知的诱惑与恐惧。',
      icon: 'Ghost',
      passiveSkill: {
        id: 'p_chaos',
        name: '不可名状',
        description: '身体构造可随心改变',
        type: 'constitution',
        icon: 'Ghost',
      },
      permanentState: {
        name: '不可名状',
        bonus: {
          魅力加成: -15,
          幸运加成: 0,
          基础性斗力加成: 0,
          基础性斗力成算: 25,
          基础忍耐力加成: 0,
          基础忍耐力成算: 25,
          闪避率加成: 0,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'o_doll',
      name: '活体人偶',
      description: '精致如人偶般的存在，痛觉迟钝，唯命是从。',
      icon: 'User',
      passiveSkill: {
        id: 'p_doll',
        name: '无心之躯',
        description: '大幅降低受到的精神伤害',
        type: 'constitution',
        icon: 'Shield',
      },
      permanentState: {
        name: '人偶之躯',
        bonus: {
          魅力加成: 30,
          幸运加成: 0,
          基础性斗力加成: 0,
          基础性斗力成算: -60,
          基础忍耐力加成: 0,
          基础忍耐力成算: 50,
          闪避率加成: 0,
          暴击率加成: 0,
        },
      },
    },
    {
      id: 'o_beast',
      name: '兽化人',
      description: '保留了野兽本能的亚人，感官敏锐，行动迅捷。',
      icon: 'Cat',
      passiveSkill: {
        id: 'p_instinct',
        name: '野性直觉',
        description: '必定闪避致命的一击',
        type: 'constitution',
        icon: 'Wind',
      },
      permanentState: {
        name: '野兽本能',
        bonus: {
          魅力加成: -8,
          幸运加成: 12,
          基础性斗力加成: 0,
          基础性斗力成算: 15,
          基础忍耐力加成: 0,
          基础忍耐力成算: 10,
          闪避率加成: 25,
          暴击率加成: 10,
        },
      },
    },
    {
      id: 'o_cyborg',
      name: '机娘',
      description: '全身义体化的改造人，拥有精密的计算能力与震动功能。',
      icon: 'Cpu',
      passiveSkill: {
        id: 'p_vibrate',
        name: '高频震动',
        description: '接触即造成持续快感伤害',
        type: 'constitution',
        icon: 'Zap',
      },
      permanentState: {
        name: '机械改造',
        bonus: {
          魅力加成: -20,
          幸运加成: -10,
          基础性斗力加成: 0,
          基础性斗力成算: 25,
          基础忍耐力加成: 0,
          基础忍耐力成算: 35,
          闪避率加成: 0,
          暴击率加成: 10,
        },
      },
    },
  ],
};

// --- Active Skills (20+) ---

export const ACTIVE_SKILLS: Skill[] = [
  {
    id: 's_strip',
    name: '衣物破坏',
    description: '【攻击】强行撕裂对方衣物',
    effectDescription: '减少对方防御',
    type: 'active',
    icon: 'Scissors',
  },
  {
    id: 's_tease',
    name: '指尖挑逗',
    description: '【攻击】精细的爱抚敏感点',
    effectDescription: '造成少量快感',
    type: 'active',
    icon: 'HandPointer',
  },
  {
    id: 's_observe',
    name: '弱点洞察',
    description: '【辅助】观察对方身体',
    effectDescription: '下回合暴击率提升',
    type: 'active',
    icon: 'Eye',
  },
  {
    id: 's_kiss',
    name: '深吻',
    description: '【攻击】交换唾液的深吻',
    effectDescription: '造成快感并封锁语言',
    type: 'active',
    icon: 'Kiss',
  },
  {
    id: 's_spank',
    name: '羞耻拍打',
    description: '【攻击】拍打臀部',
    effectDescription: '增加对方羞耻与快感',
    type: 'active',
    icon: 'Hand',
  },
  {
    id: 's_dirtytalk',
    name: '污言秽语',
    description: '【精神】用言语侮辱对方',
    effectDescription: '降低对方意志力',
    type: 'active',
    icon: 'Comment',
  },
  {
    id: 's_pheromone',
    name: '费洛蒙',
    description: '【领域】散发催情气味',
    effectDescription: '每回合持续增加快感',
    type: 'active',
    icon: 'Wind',
  },
  {
    id: 's_camera',
    name: '偷拍视角',
    description: '【精神】记录羞耻画面',
    effectDescription: '大幅降低对方意志',
    type: 'active',
    icon: 'Camera',
  },
  {
    id: 's_toy',
    name: '道具使用',
    description: '【特殊】使用随身玩具',
    effectDescription: '效果取决于道具',
    type: 'active',
    icon: 'Lightning',
  },
  {
    id: 's_foot',
    name: '足技',
    description: '【攻击】用脚挑逗',
    effectDescription: '带有羞辱性质的快感',
    type: 'active',
    icon: 'Footprints',
  },
  {
    id: 's_bind',
    name: '束缚',
    description: '【控制】限制对方行动',
    effectDescription: '降低对方闪避率',
    type: 'active',
    icon: 'Chain',
  },
  {
    id: 's_massage',
    name: '精油按摩',
    description: '【特殊】推油按摩',
    effectDescription: '降低防御，增加敏感度',
    type: 'active',
    icon: 'Droplets',
  },
  {
    id: 's_flash',
    name: '露出',
    description: '【精神】展示私密部位',
    effectDescription: '对纯情角色造成暴击',
    type: 'active',
    icon: 'Sparkles',
  },
  {
    id: 's_beg',
    name: '求饶',
    description: '【防御】楚楚可怜地求饶',
    effectDescription: '降低对方性斗力',
    type: 'active',
    icon: 'Sad',
  },
  {
    id: 's_taunt',
    name: '挑衅',
    description: '【精神】嘲讽对方的技术',
    effectDescription: '增加对方怒气但降低防御',
    type: 'active',
    icon: 'Grin',
  },
  {
    id: 's_force',
    name: '强行压制',
    description: '【控制】利用体格压制',
    effectDescription: '封锁对方物理行动',
    type: 'active',
    icon: 'Dumbbell',
  },
  {
    id: 's_deny',
    name: '寸止',
    description: '【特殊】在关键时刻停手',
    effectDescription: '积累大量压力值',
    type: 'active',
    icon: 'HandFist',
  },
  {
    id: 's_worship',
    name: '崇拜',
    description: '【精神】奉对方为主人',
    effectDescription: '回复对方意志，降低自身意志',
    type: 'active',
    icon: 'Crown',
  },
  {
    id: 's_aphrodisiac',
    name: '媚药投毒',
    description: '【道具】悄悄下药',
    effectDescription: '赋予持续发情状态',
    type: 'active',
    icon: 'Flask',
  },
  {
    id: 's_charm_kiss',
    name: '魅惑之吻',
    description: '【攻击】用魅惑的吻技攻击',
    effectDescription: '造成50%魅力伤害，降低目标意志力',
    type: 'active',
    icon: 'Heart',
  },
  {
    id: 's_counter',
    name: '快速反击',
    description: '【攻击】在闪避后立即反击',
    effectDescription: '造成80%性斗力伤害，无视防御',
    type: 'active',
    icon: 'Shield',
  },
  {
    id: 's_lucky_strike',
    name: '幸运一击',
    description: '【攻击】依靠运气发动的强力攻击',
    effectDescription: '造成60%性斗力+40%幸运伤害',
    type: 'active',
    icon: 'Clover',
  },
];

// --- Constitution/Passive Skills (Gender Specific) ---

const COMMON_PASSIVES: Skill[] = [
  {
    id: 'c_thick_skin',
    name: '钝感',
    description: '感官比较迟钝',
    effectDescription: '受到的快感伤害-30%',
    type: 'constitution',
    icon: 'Shield',
  },
  {
    id: 'c_quick_recovery',
    name: '回复体质',
    description: '体力恢复很快',
    effectDescription: '每回合回复5%耐力',
    type: 'constitution',
    icon: 'Heartbeat',
  },
  {
    id: 'c_flexible',
    name: '身体柔软',
    description: '可以做出高难度动作',
    effectDescription: '闪避率+10%，解锁特殊体位',
    type: 'constitution',
    icon: 'Yoga',
  },
  {
    id: 'c_exhibitionist',
    name: '暴露狂',
    description: '被人注视会兴奋',
    effectDescription: '围观人数越多全属性越高',
    type: 'constitution',
    icon: 'Eye',
  },
  {
    id: 'c_m_physique',
    name: 'M属性',
    description: '享受痛苦与羞辱',
    effectDescription: '受到的精神伤害转化为快感',
    type: 'constitution',
    icon: 'HeartPulse',
  },
  {
    id: 'c_s_physique',
    name: 'S属性',
    description: '以施虐为乐',
    effectDescription: '攻击造成额外精神伤害',
    type: 'constitution',
    icon: 'Crown',
  },
];

export const PASSIVE_SKILLS: Record<Gender, Skill[]> = {
  [Gender.MALE]: [
    ...COMMON_PASSIVES,
    {
      id: 'c_iron_cock',
      name: '钢铁巨根',
      description: '坚硬如铁',
      effectDescription: '攻击力+20%',
      type: 'constitution',
      icon: 'Dumbbell',
    },
    {
      id: 'c_stamina_monster',
      name: '耐力怪物',
      description: '不知疲倦',
      effectDescription: '最大耐力+100',
      type: 'constitution',
      icon: 'Lightning',
    },
    {
      id: 'c_prostate_master',
      name: '前列腺开发',
      description: '弱点开发',
      effectDescription: '后庭敏感度x3',
      type: 'constitution',
      icon: 'Target',
    },
  ],
  [Gender.FEMALE]: [
    ...COMMON_PASSIVES,
    {
      id: 'c_sensitive_nips',
      name: '乳首开发',
      description: '胸部极为敏感',
      effectDescription: '胸部受到攻击快感x2',
      type: 'constitution',
      icon: 'Target',
    },
    {
      id: 'c_wet',
      name: '淫乱体质',
      description: '极易动情',
      effectDescription: '初始快感+20，爱液分泌增加',
      type: 'constitution',
      icon: 'Droplets',
    },
    {
      id: 'c_dry',
      name: '石女/白虎',
      description: '难以动情',
      effectDescription: '快感积累速度-20%',
      type: 'constitution',
      icon: 'Snowflake',
    },
    {
      id: 'c_tongue',
      name: '名器之舌',
      description: '舌头灵活',
      effectDescription: '口技效果+50%',
      type: 'constitution',
      icon: 'Fire',
    },
    {
      id: 'c_voice',
      name: '娇喘',
      description: '声音好听',
      effectDescription: '受击时的叫声会对周围造成精神伤害',
      type: 'constitution',
      icon: 'Music',
    },
    {
      id: 'c_scent',
      name: '体香',
      description: '天生自带香气',
      effectDescription: '对手每回合意志力-2',
      type: 'constitution',
      icon: 'Seedling',
    },
  ],
  [Gender.OTHER]: [
    ...COMMON_PASSIVES,
    {
      id: 'c_sensitive_nips',
      name: '乳首开发',
      description: '胸部极为敏感',
      effectDescription: '胸部受到攻击快感x2',
      type: 'constitution',
      icon: 'Target',
    },
    {
      id: 'c_wet',
      name: '淫乱体质',
      description: '极易动情',
      effectDescription: '初始快感+20，爱液分泌增加',
      type: 'constitution',
      icon: 'Droplets',
    },
    {
      id: 'c_voice',
      name: '娇喘',
      description: '声音好听',
      effectDescription: '受击时的叫声会对周围造成精神伤害',
      type: 'constitution',
      icon: 'Music',
    },
    {
      id: 'c_scent',
      name: '体香',
      description: '天生自带香气',
      effectDescription: '对手每回合意志力-2',
      type: 'constitution',
      icon: 'Seedling',
    },
    {
      id: 'c_mutable',
      name: '不定形',
      description: '身体结构不稳定',
      effectDescription: '免疫暴击',
      type: 'constitution',
      icon: 'Ghost',
    },
  ],
};

// 属性最大值（用于角色创建时的限制）
export const MAX_STATS = {
  '角色基础._等级': 20,
  '核心状态._潜力': 10.0,
  '核心状态._魅力': 100,
  '核心状态._幸运': 100,
  '核心状态.$最大耐力': 500,
  '核心状态.$最大快感': 500,
  '核心状态.$基础性斗力': 999, // 注意：性斗力由公式计算，此值仅用于显示
  '核心状态.$基础忍耐力': 999, // 注意：忍耐力由公式计算，此值仅用于显示
  '核心状态._闪避率': 60,
  '核心状态._暴击率': 100,
};

// 属性最小值（用于角色创建时的限制）
export const MIN_STATS = {
  '角色基础._等级': 1,
  '核心状态._潜力': 5.0,
  '核心状态._魅力': 0,
  '核心状态._幸运': 0,
  '核心状态.$最大耐力': 1,
  '核心状态.$最大快感': 1,
  '核心状态.$基础性斗力': 0,
  '核心状态.$基础忍耐力': 0,
  '核心状态._闪避率': 0,
  '核心状态._暴击率': 0,
};

export const DIFFICULTY_POINTS = {
  '剧情模式 (简单)': 100,
  '学园生活 (普通)': 60,
  '地狱开局 (困难)': 30,
  作弊者: 999,
  抖M: 400,
};

export const CUP_SIZES = ['AA', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I+', 'Z'];

export const GENITAL_TYPES = {
  [Gender.MALE]: ['标准', '巨根', '短小', '包茎', '形状优美', '青筋暴露', '珍珠疹', '极粗', '倒钩', '发光'],
  [Gender.FEMALE]: ['标准', '白虎', '馒头穴', '一线天', '蝴蝶穴', '粉嫩', '色素沉淀', '多水', '紧致', '名器'],
  // 非二元角色使用男性/女性性器特征，不再有独立的选项
};
