/**
 * 战斗界面技能数据库
 * 集中存储所有技能的完整数据
 */

import { BuffType, DamageSource, SkillData, SkillType } from './types';

// ==================== 通用技能 ====================

export const COMMON_SKILLS: SkillData[] = [
  {
    id: 's_tease',
    name: '指尖挑逗',
    description: '用灵巧的指尖在对方敏感处轻柔游走',
    effectDescription: '造成60%性斗力+5快感伤害',
    icon: 'HandPointer',
    type: SkillType.PHYSICAL,
    staminaCost: 8,
    cooldown: 0,
    castTime: 0,
    damageFormula: [{ source: DamageSource.SEX_POWER, coefficient: 0.6, baseValue: 5 }],
    accuracy: 95,
    critModifier: 5,
    buffs: [{ type: BuffType.SENSITIVE, value: 15, isPercent: true, duration: 2, stackable: true, maxStacks: 3 }],
    canBeReflected: false,
    hitCount: 1,
    voiceLine: '让我来找找你的弱点...',
  },
  {
    id: 's_kiss',
    name: '深吻',
    description: '一个令人窒息的深吻,封住对方的唇舌',
    effectDescription: '造成80%性斗力+300%魅力伤害',
    icon: 'Kiss',
    type: SkillType.PHYSICAL,
    staminaCost: 12,
    cooldown: 2,
    castTime: 0,
    damageFormula: [
      { source: DamageSource.SEX_POWER, coefficient: 0.8, baseValue: 8 },
      { source: DamageSource.CHARM, coefficient: 3.0, baseValue: 0 },
    ],
    accuracy: 90,
    critModifier: 10,
    buffs: [{ type: BuffType.SILENCE, value: 0, isPercent: false, duration: 1, stackable: false }],
    canBeReflected: false,
    hitCount: 1,
    voiceLine: '嘘...安静...',
  },
  {
    id: 's_strip',
    name: '衣物破坏',
    description: '粗暴地撕裂对方的衣物',
    effectDescription: '减少对方忍耐力20%',
    icon: 'Scissors',
    type: SkillType.PHYSICAL,
    staminaCost: 10,
    cooldown: 3,
    castTime: 0,
    damageFormula: [{ source: DamageSource.SEX_POWER, coefficient: 0.4, baseValue: 3 }],
    accuracy: 85,
    critModifier: 0,
    buffs: [{ type: BuffType.DEF_DOWN, value: 20, isPercent: true, duration: 99, stackable: true, maxStacks: 5 }],
    canBeReflected: false,
    hitCount: 1,
    voiceLine: '穿这么多干嘛?',
  },
  {
    id: 's_spank',
    name: '羞耻拍打',
    description: '用力拍打对方的臀部',
    effectDescription: '造成50%性斗力+4伤害,附加羞耻状态',
    icon: 'Hand',
    type: SkillType.PHYSICAL,
    staminaCost: 6,
    cooldown: 1,
    castTime: 0,
    damageFormula: [{ source: DamageSource.SEX_POWER, coefficient: 0.5, baseValue: 4 }],
    accuracy: 100,
    critModifier: 15,
    buffs: [{ type: BuffType.SHAME, value: 8, isPercent: false, duration: 2, stackable: true, maxStacks: 5 }],
    canBeReflected: false,
    hitCount: 1,
    voiceLine: '听这声音,真是色情呢...',
  },
  {
    id: 's_dirtytalk',
    name: '污言秽语',
    description: '用下流的言语刺激对方',
    effectDescription: '造成500%魅力伤害,降低意志力5%',
    icon: 'Comment',
    type: SkillType.MENTAL,
    staminaCost: 5,
    cooldown: 0,
    castTime: 0,
    damageFormula: [{ source: DamageSource.CHARM, coefficient: 5.0, baseValue: 3 }],
    accuracy: 100,
    critModifier: 5,
    buffs: [{ type: BuffType.SENSITIVE, value: 5, isPercent: true, duration: 2, stackable: true, maxStacks: 4 }],
    canBeReflected: false,
    hitCount: 1,
    voiceLine: '你这个淫乱的家伙...',
  },
  {
    id: 's_observe',
    name: '弱点洞察',
    description: '仔细观察对方的反应',
    effectDescription: '下次攻击暴击率+50%',
    icon: 'Eye',
    type: SkillType.SUPPORT,
    staminaCost: 6,
    cooldown: 3,
    castTime: 0,
    damageFormula: [],
    accuracy: 100,
    critModifier: 0,
    buffs: [
      { type: BuffType.FOCUS, value: 50, isPercent: true, duration: 1, stackable: false },
      { type: BuffType.CRIT_UP, value: 30, isPercent: true, duration: 2, stackable: false },
    ],
    canBeReflected: false,
    hitCount: 0,
    voiceLine: '找到了...',
  },
  {
    id: 's_taunt',
    name: '嘲讽挑衅',
    description: '用轻蔑的语气嘲讽对方',
    effectDescription: '对方攻击+20%但防御-25%',
    icon: 'Ghost',
    staminaCost: 8,
    cooldown: 2,
    castTime: 0,
    damageFormula: [{ source: DamageSource.CHARM, coefficient: 3.0, baseValue: 2 }],
    accuracy: 100,
    critModifier: 0,
    buffs: [
      { type: BuffType.ATK_UP, value: 20, isPercent: true, duration: 2, stackable: false },
      { type: BuffType.DEF_DOWN, value: 25, isPercent: true, duration: 2, stackable: false },
    ],
    canBeReflected: false,
    hitCount: 1,
    voiceLine: '就这?杂鱼~',
  },
  {
    id: 's_rest',
    name: '喘息',
    description: '短暂的休息来恢复体力',
    effectDescription: '恢复15%耐力,防御提升15%',
    icon: 'Bed',
    type: SkillType.SUPPORT,
    staminaCost: 0,
    cooldown: 4,
    castTime: 0,
    damageFormula: [],
    accuracy: 100,
    critModifier: 0,
    buffs: [
      { type: BuffType.REGEN, value: 15, isPercent: true, duration: 2, stackable: false },
      { type: BuffType.DEF_UP, value: 15, isPercent: true, duration: 2, stackable: false },
    ],
    canBeReflected: false,
    hitCount: 0,
    voiceLine: '让我歇一下...',
  },
];

// ==================== 高级技能 ====================

export const ADVANCED_SKILLS: SkillData[] = [
  {
    id: 's_massage',
    name: '精油按摩',
    description: '涂抹精油进行全身按摩',
    effectDescription: '造成120%性斗力伤害,防御-15%,敏感+25%',
    icon: 'Droplets',
    type: SkillType.PHYSICAL,
    staminaCost: 18,
    cooldown: 4,
    castTime: 1,
    damageFormula: [{ source: DamageSource.SEX_POWER, coefficient: 1.2, baseValue: 10 }],
    accuracy: 100,
    critModifier: 0,
    buffs: [
      { type: BuffType.DEF_DOWN, value: 15, isPercent: true, duration: 3, stackable: false },
      { type: BuffType.SENSITIVE, value: 25, isPercent: true, duration: 3, stackable: false },
    ],
    canBeReflected: false,
    hitCount: 1,
    voiceLine: '放松...让我来服侍你...',
  },
  {
    id: 's_bind',
    name: '束缚',
    description: '用绳索限制对方行动',
    effectDescription: '造成30%性斗力伤害,束缚2回合',
    icon: 'Chain',
    type: SkillType.CONTROL,
    staminaCost: 18,
    cooldown: 5,
    castTime: 0,
    damageFormula: [{ source: DamageSource.SEX_POWER, coefficient: 0.3, baseValue: 5 }],
    accuracy: 80,
    critModifier: 0,
    buffs: [
      { type: BuffType.BIND, value: 0, isPercent: false, duration: 2, stackable: false },
      { type: BuffType.DODGE_DOWN, value: 30, isPercent: true, duration: 2, stackable: false },
    ],
    canBeReflected: false,
    hitCount: 1,
    voiceLine: '乖乖不要动...',
  },
  {
    id: 's_pheromone',
    name: '费洛蒙',
    description: '释放催情气息',
    effectDescription: '使对方进入发情状态',
    icon: 'Wind',
    type: SkillType.CHARM,
    staminaCost: 20,
    cooldown: 5,
    castTime: 0,
    damageFormula: [{ source: DamageSource.CHARM, coefficient: 3.0, baseValue: 0 }],
    accuracy: 100,
    critModifier: 0,
    buffs: [{ type: BuffType.HEAT, value: 10, isPercent: false, duration: 4, stackable: false }],
    canBeReflected: false,
    hitCount: 1,
    voiceLine: '闻到了吗?这就是我的味道...',
  },
];

// ==================== 所有技能 ====================

export const ALL_SKILLS: SkillData[] = [...COMMON_SKILLS, ...ADVANCED_SKILLS];

/** 按ID获取技能 */
export function getSkillById(id: string): SkillData | undefined {
  return ALL_SKILLS.find(skill => skill.id === id);
}

/** 按类型获取技能 */
export function getSkillsByType(type: SkillType): SkillData[] {
  return ALL_SKILLS.filter(skill => skill.type === type);
}
